apiVersion: apps/v1
kind: Deployment
metadata:
  name: kravix-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: kravix-app

  template:
    metadata:
      labels:
        app: kravix-app

    spec:
      containers:
      - name: kravix-app
        image: laharikalva/kravix-app:v1

        ports:
        - containerPort: 80